# datos que se requiere
aforo = 0
# Lista de reservaciones de restaurante
mesa = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
        31, 32, 33, 34, 35, 36, 37, 38, 39, 40]
mesa_disponible = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
dia = ["lunes", "martes", "miercoles", "jueves", "viernes", "sabado", "domingo"]
desayuno = [6, 7, 8, 9, 10, 11]
almuerzo = [11, 12, 1, 2, 3, 4]
cena = [4, 5, 6, 7, 8, 9, 10]
# bienvenida al modulo de restaurantes el descanso
print("\t\t\tBienvenido a los restaurante de la cadena de hoteles el descanso\t\t\t ")
print(",seleccione uno de nuestros restaurante que desea reservar")
print("1- Restauran el descanso-puntarenas")
print("2- Restauran el descanso-Sancarlos")
print("3- Restauran el descanso-Guanacaste")
seleccion_restauran = int(input("Digite el numero en que desea reservar: "))
if seleccion_restauran == 1:
    print("\t\t\tEl restaurante el descanso Puntarena le da la bienvenida\t\t\t")
    print("Seleccione los dias que desea reservar en el restaurante el descanso")
    print()
    p = str(input("Escriba el dia que desea reservar"))
    print()
    print(dia[0], end="\t")
    print(dia[1], end="\t")
    print(dia[2], end="\t")
    print(dia[3], end="\t")
    print(dia[4], end="\t")
    print(dia[5], end="\t")
    print(dia[6], end="\t")
    print()
    if p == dia[0]:
        print("hora disponible en el desayuno del dia lunes")
        print(desayuno[0], end="\t")
        print(desayuno[1], end="\t")
        print(desayuno[2], end="\t")
        print(desayuno[3], end="\t")
        print(desayuno[4], end="\t")
        print(desayuno[5])
        print("hora disponible en el almuerzo del dia lunes")
        print(almuerzo[0], end="\t")
        print(almuerzo[1], end="\t")
        print(almuerzo[2], end="\t")
        print(almuerzo[3], end="\t")
        print(almuerzo[4], end="\t")
        print(almuerzo[5])
        print("Hora disponible de la cena del dia lunes")
        print(cena[0], end="\t")
        print(cena[1], end="\t")
        print(cena[2], end="\t")
        print(cena[3], end="\t")
        print(cena[4], end="\t")
        print(cena[5], end="\t")
        print(cena[6])

    if p == dia[1]:
        print("hora disponible en el desayuno del dia Martes")
        print(desayuno[0], end="\t")
        print(desayuno[1], end="\t")
        print(desayuno[2], end="\t")
        print(desayuno[3], end="\t")
        print(desayuno[4], end="\t")
        print(desayuno[5])
        print("hora disponible en el almuerzo del dia martes")
        print(almuerzo[0], end="\t")
        print(almuerzo[1], end="\t")
        print(almuerzo[2], end="\t")
        print(almuerzo[3], end="\t")
        print(almuerzo[4], end="\t")
        print(almuerzo[5])
        print("Hora disponible de la cena del dia martes")
        print(cena[0], end="\t")
        print(cena[1], end="\t")
        print(cena[2], end="\t")
        print(cena[3], end="\t")
        print(cena[4], end="\t")
        print(cena[5], end="\t")
        print(cena[6])

    if p == dia[2]:
        print("hora disponible en el desayuno del dia miercoles")
        print(desayuno[0], end="\t")
        print(desayuno[1], end="\t")
        print(desayuno[2], end="\t")
        print(desayuno[3], end="\t")
        print(desayuno[4], end="\t")
        print(desayuno[5])
        print("hora disponible en el almuerzo del dia miercoles")
        print(almuerzo[0], end="\t")
        print(almuerzo[1], end="\t")
        print(almuerzo[2], end="\t")
        print(almuerzo[3], end="\t")
        print(almuerzo[4], end="\t")
        print(almuerzo[5])
        print("Hora disponible de la cena del dia miercoles")
        print(cena[0], end="\t")
        print(cena[1], end="\t")
        print(cena[2], end="\t")
        print(cena[3], end="\t")
        print(cena[4], end="\t")
        print(cena[5], end="\t")
        print(cena[6])

    if p == dia[3]:
        print("hora disponible en el desayuno del dia Jueves")
        print(desayuno[0], end="\t")
        print(desayuno[1], end="\t")
        print(desayuno[2], end="\t")
        print(desayuno[3], end="\t")
        print(desayuno[4], end="\t")
        print(desayuno[5])
        print("hora disponible en el almuerzo del dia Jueves")
        print(almuerzo[0], end="\t")
        print(almuerzo[1], end="\t")
        print(almuerzo[2], end="\t")
        print(almuerzo[3], end="\t")
        print(almuerzo[4], end="\t")
        print(almuerzo[5])
        print("Hora disponible de la cena del dia Jueves")
        print(cena[0], end="\t")
        print(cena[1], end="\t")
        print(cena[2], end="\t")
        print(cena[3], end="\t")
        print(cena[4], end="\t")
        print(cena[5], end="\t")
        print(cena[6])

    if p == dia[4]:
        print("hora disponible en el desayuno del dia Viernes")
        print(desayuno[0], end="\t")
        print(desayuno[1], end="\t")
        print(desayuno[2], end="\t")
        print(desayuno[3], end="\t")
        print(desayuno[4], end="\t")
        print(desayuno[5])
        print("hora disponible en el almuerzo del dia Viernes")
        print(almuerzo[0], end="\t")
        print(almuerzo[1], end="\t")
        print(almuerzo[2], end="\t")
        print(almuerzo[3], end="\t")
        print(almuerzo[4], end="\t")
        print(almuerzo[5])
        print("Hora disponible de la cena del dia Viernes")
        print(cena[0], end="\t")
        print(cena[1], end="\t")
        print(cena[2], end="\t")
        print(cena[3], end="\t")
        print(cena[4], end="\t")
        print(cena[5], end="\t")
        print(cena[6])

    if p == dia[5]:
        print("hora disponible en el desayuno del dia Sabado")
        print()
        print(desayuno[0], end="\t")
        print(desayuno[1], end="\t")
        print(desayuno[2], end="\t")
        print(desayuno[3], end="\t")
        print(desayuno[4], end="\t")
        print(desayuno[5])
        print()
        print("hora disponible en el almuerzo del dia Sabado")
        print(almuerzo[0], end="\t")
        print(almuerzo[1], end="\t")
        print(almuerzo[2], end="\t")
        print(almuerzo[3], end="\t")
        print(almuerzo[4], end="\t")
        print(almuerzo[5])
        print("Hora disponible de la cena del dia Sabado")
        print(cena[0], end="\t")
        print(cena[1], end="\t")
        print(cena[2], end="\t")
        print(cena[3], end="\t")
        print(cena[4], end="\t")
        print(cena[5], end="\t")
        print(cena[6])
        print()
    if p == dia[6]:
        print("hora disponible en el desayuno del dia Domingo")
        print(desayuno[0], end="\t")
        print(desayuno[1], end="\t")
        print(desayuno[2], end="\t")
        print(desayuno[3], end="\t")
        print(desayuno[4], end="\t")
        print(desayuno[5])
        print("hora disponible en el almuerzo del dia Domingo")
        print(almuerzo[0], end="\t")
        print(almuerzo[1], end="\t")
        print(almuerzo[2], end="\t")
        print(almuerzo[3], end="\t")
        print(almuerzo[4], end="\t")
        print(almuerzo[5])
        print("Hora disponible de la cena del dia Domingo")
        print(cena[0], end="\t")
        print(cena[1], end="\t")
        print(cena[2], end="\t")
        print(cena[3], end="\t")
        print(cena[4], end="\t")
        print(cena[5], end="\t")
        print(cena[6])
        print("El tiempo maximo que se le dara al cliente es de una hora en el restaurante")

if seleccion_restauran == 2:
    print("\t\t\tEl restaurante el descanso San Carlos le da la bienvenida\t\t\t")
    print("Seleccione los dias que desea reservar en el restaurante el descanso")
    print()
    s = str(input("Escriba el dia que desea reservar"))
    print()
    print(dia[0], end="\t")
    print(dia[1], end="\t")
    print(dia[2], end="\t")
    print(dia[3], end="\t")
    print(dia[4], end="\t")
    print(dia[5], end="\t")
    print(dia[6], end="\t")
    print()
    if s == dia[0]:
        print("hora disponible en el desayuno del dia lunes")
        print(desayuno[0], end="\t")
        print(desayuno[1], end="\t")
        print(desayuno[2], end="\t")
        print(desayuno[3], end="\t")
        print(desayuno[4], end="\t")
        print(desayuno[5])
        print("hora disponible en el almuerzo del dia lunes")
        print(almuerzo[0], end="\t")
        print(almuerzo[1], end="\t")
        print(almuerzo[2], end="\t")
        print(almuerzo[3], end="\t")
        print(almuerzo[4], end="\t")
        print(almuerzo[5])
        print("Hora disponible de la cena del dia lunes")
        print(cena[0], end="\t")
        print(cena[1], end="\t")
        print(cena[2], end="\t")
        print(cena[3], end="\t")
        print(cena[4], end="\t")
        print(cena[5], end="\t")
        print(cena[6])

    if s == dia[1]:
        print("hora disponible en el desayuno del dia Martes")
        print(desayuno[0], end="\t")
        print(desayuno[1], end="\t")
        print(desayuno[2], end="\t")
        print(desayuno[3], end="\t")
        print(desayuno[4], end="\t")
        print(desayuno[5])
        print("hora disponible en el almuerzo del dia martes")
        print(almuerzo[0], end="\t")
        print(almuerzo[1], end="\t")
        print(almuerzo[2], end="\t")
        print(almuerzo[3], end="\t")
        print(almuerzo[4], end="\t")
        print(almuerzo[5])
        print("Hora disponible de la cena del dia martes")
        print(cena[0], end="\t")
        print(cena[1], end="\t")
        print(cena[2], end="\t")
        print(cena[3], end="\t")
        print(cena[4], end="\t")
        print(cena[5], end="\t")
        print(cena[6])

    if s == dia[2]:
        print("hora disponible en el desayuno del dia miercoles")
        print(desayuno[0], end="\t")
        print(desayuno[1], end="\t")
        print(desayuno[2], end="\t")
        print(desayuno[3], end="\t")
        print(desayuno[4], end="\t")
        print(desayuno[5])
        print("hora disponible en el almuerzo del dia miercoles")
        print(almuerzo[0], end="\t")
        print(almuerzo[1], end="\t")
        print(almuerzo[2], end="\t")
        print(almuerzo[3], end="\t")
        print(almuerzo[4], end="\t")
        print(almuerzo[5])
        print("Hora disponible de la cena del dia miercoles")
        print(cena[0], end="\t")
        print(cena[1], end="\t")
        print(cena[2], end="\t")
        print(cena[3], end="\t")
        print(cena[4], end="\t")
        print(cena[5], end="\t")
        print(cena[6])

    if s == dia[3]:
        print("hora disponible en el desayuno del dia Jueves")
        print(desayuno[0], end="\t")
        print(desayuno[1], end="\t")
        print(desayuno[2], end="\t")
        print(desayuno[3], end="\t")
        print(desayuno[4], end="\t")
        print(desayuno[5])
        print("hora disponible en el almuerzo del dia Jueves")
        print(almuerzo[0], end="\t")
        print(almuerzo[1], end="\t")
        print(almuerzo[2], end="\t")
        print(almuerzo[3], end="\t")
        print(almuerzo[4], end="\t")
        print(almuerzo[5])
        print("Hora disponible de la cena del dia Jueves")
        print(cena[0], end="\t")
        print(cena[1], end="\t")
        print(cena[2], end="\t")
        print(cena[3], end="\t")
        print(cena[4], end="\t")
        print(cena[5], end="\t")
        print(cena[6])

    if s == dia[4]:
        print("hora disponible en el desayuno del dia Viernes")
        print(desayuno[0], end="\t")
        print(desayuno[1], end="\t")
        print(desayuno[2], end="\t")
        print(desayuno[3], end="\t")
        print(desayuno[4], end="\t")
        print(desayuno[5])
        print("hora disponible en el almuerzo del dia Viernes")
        print(almuerzo[0], end="\t")
        print(almuerzo[1], end="\t")
        print(almuerzo[2], end="\t")
        print(almuerzo[3], end="\t")
        print(almuerzo[4], end="\t")
        print(almuerzo[5])
        print("Hora disponible de la cena del dia Viernes")
        print(cena[0], end="\t")
        print(cena[1], end="\t")
        print(cena[2], end="\t")
        print(cena[3], end="\t")
        print(cena[4], end="\t")
        print(cena[5], end="\t")
        print(cena[6])

    if s == dia[5]:
        print("hora disponible en el desayuno del dia Sabado")
        print()
        print(desayuno[0], end="\t")
        print(desayuno[1], end="\t")
        print(desayuno[2], end="\t")
        print(desayuno[3], end="\t")
        print(desayuno[4], end="\t")
        print(desayuno[5])
        print()
        print("hora disponible en el almuerzo del dia Sabado")
        print(almuerzo[0], end="\t")
        print(almuerzo[1], end="\t")
        print(almuerzo[2], end="\t")
        print(almuerzo[3], end="\t")
        print(almuerzo[4], end="\t")
        print(almuerzo[5])
        print("Hora disponible de la cena del dia Sabado")
        print(cena[0], end="\t")
        print(cena[1], end="\t")
        print(cena[2], end="\t")
        print(cena[3], end="\t")
        print(cena[4], end="\t")
        print(cena[5], end="\t")
        print(cena[6])
        print()
    if s == dia[6]:
        print("hora disponible en el desayuno del dia Domingo")
        print(desayuno[0], end="\t")
        print(desayuno[1], end="\t")
        print(desayuno[2], end="\t")
        print(desayuno[3], end="\t")
        print(desayuno[4], end="\t")
        print(desayuno[5])
        print("hora disponible en el almuerzo del dia Domingo")
        print(almuerzo[0], end="\t")
        print(almuerzo[1], end="\t")
        print(almuerzo[2], end="\t")
        print(almuerzo[3], end="\t")
        print(almuerzo[4], end="\t")
        print(almuerzo[5])
        print("Hora disponible de la cena del dia Domingo")
        print(cena[0], end="\t")
        print(cena[1], end="\t")
        print(cena[2], end="\t")
        print(cena[3], end="\t")
        print(cena[4], end="\t")
        print(cena[5], end="\t")
        print(cena[6])
        print("El tiempo maximo que se le dara al cliente es de una hora en el restaurante")

if seleccion_restauran == 3:
    print("\t\t\tEl restaurante el descanso Guanacaste le da la bienvenida\t\t\t")
    print("Seleccione los dias que desea reservar en el restaurante el descanso")
    print()
    print(dia[0], end="\t")
    print(dia[1], end="\t")
    print(dia[2], end="\t")
    print(dia[3], end="\t")
    print(dia[4], end="\t")
    print(dia[5], end="\t")
    print(dia[6], end="\t")
    print()
    g = str(input("Escriba el dia que desea reservar"))
    if g == dia[0]:
        print("hora disponible en el desayuno del dia lunes")
        print(desayuno[0], end="\t")
        print(desayuno[1], end="\t")
        print(desayuno[2], end="\t")
        print(desayuno[3], end="\t")
        print(desayuno[4], end="\t")
        print(desayuno[5])
        print("hora disponible en el almuerzo del dia lunes")
        print(almuerzo[0], end="\t")
        print(almuerzo[1], end="\t")
        print(almuerzo[2], end="\t")
        print(almuerzo[3], end="\t")
        print(almuerzo[4], end="\t")
        print(almuerzo[5])
        print("Hora disponible de la cena del dia lunes")
        print(cena[0], end="\t")
        print(cena[1], end="\t")
        print(cena[2], end="\t")
        print(cena[3], end="\t")
        print(cena[4], end="\t")
        print(cena[5], end="\t")
        print(cena[6])

    if g == dia[1]:
        print("hora disponible en el desayuno del dia Martes")
        print(desayuno[0], end="\t")
        print(desayuno[1], end="\t")
        print(desayuno[2], end="\t")
        print(desayuno[3], end="\t")
        print(desayuno[4], end="\t")
        print(desayuno[5])
        print("hora disponible en el almuerzo del dia martes")
        print(almuerzo[0], end="\t")
        print(almuerzo[1], end="\t")
        print(almuerzo[2], end="\t")
        print(almuerzo[3], end="\t")
        print(almuerzo[4], end="\t")
        print(almuerzo[5])
        print("Hora disponible de la cena del dia martes")
        print(cena[0], end="\t")
        print(cena[1], end="\t")
        print(cena[2], end="\t")
        print(cena[3], end="\t")
        print(cena[4], end="\t")
        print(cena[5], end="\t")
        print(cena[6])

    if g == dia[2]:
        print("hora disponible en el desayuno del dia miercoles")
        print(desayuno[0], end="\t")
        print(desayuno[1], end="\t")
        print(desayuno[2], end="\t")
        print(desayuno[3], end="\t")
        print(desayuno[4], end="\t")
        print(desayuno[5])
        print("hora disponible en el almuerzo del dia miercoles")
        print(almuerzo[0], end="\t")
        print(almuerzo[1], end="\t")
        print(almuerzo[2], end="\t")
        print(almuerzo[3], end="\t")
        print(almuerzo[4], end="\t")
        print(almuerzo[5])
        print("Hora disponible de la cena del dia miercoles")
        print(cena[0], end="\t")
        print(cena[1], end="\t")
        print(cena[2], end="\t")
        print(cena[3], end="\t")
        print(cena[4], end="\t")
        print(cena[5], end="\t")
        print(cena[6])

    if g == dia[3]:
        print("hora disponible en el desayuno del dia Jueves")
        print(desayuno[0], end="\t")
        print(desayuno[1], end="\t")
        print(desayuno[2], end="\t")
        print(desayuno[3], end="\t")
        print(desayuno[4], end="\t")
        print(desayuno[5])
        print("hora disponible en el almuerzo del dia Jueves")
        print(almuerzo[0], end="\t")
        print(almuerzo[1], end="\t")
        print(almuerzo[2], end="\t")
        print(almuerzo[3], end="\t")
        print(almuerzo[4], end="\t")
        print(almuerzo[5])
        print("Hora disponible de la cena del dia Jueves")
        print(cena[0], end="\t")
        print(cena[1], end="\t")
        print(cena[2], end="\t")
        print(cena[3], end="\t")
        print(cena[4], end="\t")
        print(cena[5], end="\t")
        print(cena[6])

    if g == dia[4]:
        print("hora disponible en el desayuno del dia Viernes")
        print(desayuno[0], end="\t")
        print(desayuno[1], end="\t")
        print(desayuno[2], end="\t")
        print(desayuno[3], end="\t")
        print(desayuno[4], end="\t")
        print(desayuno[5])
        print("hora disponible en el almuerzo del dia Viernes")
        print(almuerzo[0], end="\t")
        print(almuerzo[1], end="\t")
        print(almuerzo[2], end="\t")
        print(almuerzo[3], end="\t")
        print(almuerzo[4], end="\t")
        print(almuerzo[5])
        print("Hora disponible de la cena del dia Viernes")
        print(cena[0], end="\t")
        print(cena[1], end="\t")
        print(cena[2], end="\t")
        print(cena[3], end="\t")
        print(cena[4], end="\t")
        print(cena[5], end="\t")
        print(cena[6])

    if g == dia[5]:
        print("hora disponible en el desayuno del dia Sabado")
        print()
        print(desayuno[0], end="\t")
        print(desayuno[1], end="\t")
        print(desayuno[2], end="\t")
        print(desayuno[3], end="\t")
        print(desayuno[4], end="\t")
        print(desayuno[5])
        print()
        print("hora disponible en el almuerzo del dia Sabado")
        print(almuerzo[0], end="\t")
        print(almuerzo[1], end="\t")
        print(almuerzo[2], end="\t")
        print(almuerzo[3], end="\t")
        print(almuerzo[4], end="\t")
        print(almuerzo[5])
        print("Hora disponible de la cena del dia Sabado")
        print(cena[0], end="\t")
        print(cena[1], end="\t")
        print(cena[2], end="\t")
        print(cena[3], end="\t")
        print(cena[4], end="\t")
        print(cena[5], end="\t")
        print(cena[6])
        print()
    if g == dia[6]:
        print("hora disponible en el desayuno del dia Domingo")
        print(desayuno[0], end="\t")
        print(desayuno[1], end="\t")
        print(desayuno[2], end="\t")
        print(desayuno[3], end="\t")
        print(desayuno[4], end="\t")
        print(desayuno[5])
        print("hora disponible en el almuerzo del dia Domingo")
        print(almuerzo[0], end="\t")
        print(almuerzo[1], end="\t")
        print(almuerzo[2], end="\t")
        print(almuerzo[3], end="\t")
        print(almuerzo[4], end="\t")
        print(almuerzo[5])
        print("Hora disponible de la cena del dia Domingo")
        print(cena[0], end="\t")
        print(cena[1], end="\t")
        print(cena[2], end="\t")
        print(cena[3], end="\t")
        print(cena[4], end="\t")
        print(cena[5], end="\t")
        print(cena[6])
        print("El tiempo maximo que se le dara al cliente es de una hora en el restaurante")
        gg = int(input("Digite la mesa que desea reservar")
        if gg <= 20:
